name: infinity_store
description: App Flutter para Infinity Store
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Paquetes segÃºn pubspec.lock
  async: 2.8.2
  boolean_selector: 2.1.0
  characters: 1.2.0
  charcode: 1.3.1
  clock: 1.1.0
  collection: 1.15.0
  fake_async: 1.2.0
  matcher: 0.12.11
  material_color_utilities: 0.1.3
  meta: 1.7.0
  path: 1.8.0
  source_span: 1.8.1
  stack_trace: 1.10.0
  stream_channel: 2.1.0
  string_scanner: 1.1.0
  term_glyph: 1.2.0
  test_api: 0.4.8
  typed_data: 1.3.0
  vector_math: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
 

flutter:
  uses-material-design: true

